name: CMake CI

on:
  push:
    branches:
      - '**/*develop*'
      - '**/*master*'
  pull_request:
    branches:
      - '**/*develop*'
      - '**/*master*'

jobs:
  cross_build:
    name: Build and Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup CMake
        uses: kitware/setup-cmake@v3
        with:
          cmake-version: 'latest'

      - name: Run CI script (Linux/macOS)
        if: matrix.os != 'windows-latest'
        run: |
          chmod +x ./ci.sh
          ./ci.sh

      - name: Run CI script (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          ci.bat
        shell: cmd

      - name: Build Success
        if: success()
        run: echo "âœ… Build succeeded"

      - name: Upload build artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: build-output-${{ matrix.os }}
          path: build
